default_config:

virtual:

switch:
  - platform: virtual
    name: '!occupancy button'
    initial_value: 'off'

cover:
  - platform: virtual
    name: '!my cover'

binary_sensor:
  - platform: virtual
    name: '!occupancy'
    class: occupancy

group:
  living-room:
    name: Living Room
    entities:
      # Devices
      - switch.occupancy_button
      - cover.my_cover
      # Attributes
      - binary_sensor.occupancy

automation:
- trigger:
  - platform: state
    entity_id: switch.occupancy_button
    to: 'on'
  - platform: state
    entity_id: switch.occupancy_button
    to: 'off'
  action:
  - service: virtual.turn_{{ trigger.to_state.state }}
    target:
      entity_id: binary_sensor.occupancy

- trigger:
  - platform: state
    entity_id: binary_sensor.occupancy
    to: 'on'
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.my_cover

- trigger:
  - platform: state
    entity_id: binary_sensor.occupancy
    to: 'off'
  action:
  - service: cover.close_cover
    target:
      entity_id: cover.my_cover
