default_config:

virtual:

switch:
  - platform: virtual
    name: '!occupancy button'
    initial_value: 'off'

cover:
  - platform: virtual
    name: '!my cover'

binary_sensor:
  - platform: virtual
    name: '!occupancy'
    class: occupancy

group:
  living-room:
    name: Living Room
    entities:
      # Devices
      - switch.occupancy_button
      - cover.my_cover
      # Attributes
      - binary_sensor.occupancy

automation: !include automations.yaml
