default_config:

virtual:

switch:
  - platform: virtual
    name: Occupancy
    initial_value: 'off'

light:
  - platform: virtual
    name: Lamp
    initial_value: 'off'

binary_sensor:
  - platform: virtual
    name: Is occupied
    class: occupancy
    initial_value: 'off'
    initial_availability: True

group:
  living-room:
    name: Living Room
    entities:
      # Devices
      - switch.virtual_occupancy
      - light.virtual_lamp
      # Attributes
      - binary_sensor.virtual_is_occupied

automation: !include automations.yaml
