default_config:

virtual:

switch:
  - platform: virtual
    name: '!occupancy_button'
    initial_value: 'off'

binary_sensor:
  - platform: virtual
    name: "!oc1"
    class: occupancy

light:
  - platform: virtual
    name: "!light1"

cover:
  - platform: virtual
    name: "!cover1"

group:
  office23:
    name: chatGPT
    entities:
      - light.light1
      - cover.cover1
      - binary_sensor.0c1



# switch:
#   - platform: virtual
#     name: '!occupancy button'
#     initial_value: 'off'

# cover:
#   - platform: virtual
#     name: '!my cover'

# binary_sensor:
#   - platform: virtual
#     name: '!occupancy'
#     class: occupancy

# group:
#   living-room:
#     name: Living Room
#     entities:
#       # Devices
#       - switch.occupancy_button
#       - cover.my_cover
#       # Attributes
#       - binary_sensor.occupancy

automation: !include automations.yaml
