default_config:

virtual:

switch:
  - platform: virtual
    name: '!desk_occupancy_button'
    initial_value: 'off'
  - platform: virtual
    name: '!meetings_occupancy_button'
    initial_value: 'off'

binary_sensor:
  - platform: virtual
    name: "!deskoccupancysensor23"
    class: occupancy
  - platform: virtual
    name: "!meetingsoccupancysensor23"
    class: occupancy

light:
  - platform: virtual
    name: "!desklight23"
  - platform: virtual
    name: "!meetingslight23"

cover:
  - platform: virtual
    name: "!deskblinds23"
  - platform: virtual
    name: "!meetingsblinds23"

group:
  office23:
    name: Office 23
    entities:
      - light.desklight23
      - light.meetingslight23
      - cover.deskblinds23
      - cover.meetingsblinds23
      - binary_sensor.deskoccupancysensor23
      - binary_sensor.meetingsoccupancysensor23



# switch:
#   - platform: virtual
#     name: '!occupancy button'
#     initial_value: 'off'

# cover:
#   - platform: virtual
#     name: '!my cover'

# binary_sensor:
#   - platform: virtual
#     name: '!occupancy'
#     class: occupancy

# group:
#   living-room:
#     name: Living Room
#     entities:
#       # Devices
#       - switch.occupancy_button
#       - cover.my_cover
#       # Attributes
#       - binary_sensor.occupancy

automation: !include automations.yaml
