default_config:

virtual:

switch:
  - platform: virtual
    name: Occupancy
    initial_value: 'off'

cover:
  - platform: virtual
    name: Cover

binary_sensor:
  - platform: virtual
    name: Is occupied
    class: occupancy

group:
  living-room:
    name: Living Room
    entities:
      # Devices
      - switch.virtual_occupancy
      - cover.virtual_cover
      # Attributes
      - binary_sensor.virtual_is_occupied

automation: !include automations.yaml
