version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./ha:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
